---
apiVersion: v1
kind: ConfigMap
metadata:
  name: northwindapp-configmap
  namespace: northwind-system
data:
  DB_HOST: northwinddb-service.northwind-system.svc.cluster.local
  DB_PORT: "3306"
  DB_USER: root

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: northwindapp-deployment
  namespace: northwind-system
  labels:
    name: northwindapp-deployment
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      name: northwindapp-pod
  template:
    metadata:
      name: northwindapp-pod
      labels:
        name: northwindapp-pod
    spec:
      containers:
        - name: northwindapp-container
          image: stackupiss/northwind-app:v1
          imagePullPolicy: Always
          ports:
            - name: nwapp-http
              containerPort: 3000
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: northwinddb-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: northwindapp-configmap
          resources:
            requests:
              cpu: 100m
              memory: 16Mi

---
apiVersion: v1
kind: Service
metadata:
  name: northwindapp-service
  namespace: northwind-system
  labels:
    name: weather-service
spec:
  type: LoadBalancer
  selector:
    name: northwindapp-pod
  ports:
    - name: http
      port: 80
      targetPort: nwapp-http